import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientTopBarWrapper from "../components/ClientTopBarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Leeterview",
  description: "Generated by create next app",
  icons: {
    icon: "/images/leeterview_icon.png",
    shortcut: "/images/leeterview_icon.png",
    apple: "/images/leeterview_icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 導航欄交由 Client Component 處理 */}
        <ClientTopBarWrapper />
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
